name: Deploy Production Version

on:
  pull_request_target:
    types:
      - closed
    branches:
      - main

jobs:
  building-and-deploy-on-hub:
    if: github.event.pull_request.merged == true
    name: Build & Publish Aguia Project
    runs-on: ubuntu-latest
    env:
      CI: false
      DOT_ENV: ${{ secrets.DOT_ENV }}
      PRIVATE_KEY: ${{ secrets.SSH_PROD_PRIVATE_KEY }}
      SERVER_ADDRESS: ec2-15-229-88-93.sa-east-1.compute.amazonaws.com

    steps:
      - uses: actions/checkout@v2

      - name: Building production project
        run: |
          npm install
          npm run build

      - name: Publishing on EC2
        run: |
          export DOCKER_HOST="ssh://ubuntu@$SERVER_ADDRESS"

          echo "$PRIVATE_KEY" > ./key.pem
          chmod 400 ./key.pem
          eval $(ssh-agent)
          ssh-add -k ./key.pem

          mkdir -p ~/.ssh && echo "Host *" > ~/.ssh/config && echo " StrictHostKeyChecking no" >> ~/.ssh/config

          echo "$DOT_ENV" > ./.env

          scp -r \
            -i ./key.pem \
            ./dist ./Dockerfile ./package.json ./package-lock.json ./.env \
            ubuntu@$SERVER_ADDRESS:/var/www/api

          docker image build \
            -t aguia-real \
            -f Dockerfile .

          echo "docker image successfully build"

          echo "$(docker container stop aguia-real) was stopped" || echo "none container was stopped"
          echo "$(docker container rm aguia-real) was removed" || echo "none container was removed"

          docker run -d \
            -p 49160:3001 \
            -v /var/log/api:/usr/src/logs \
            --name aguia-real \
            aguia-real:latest

          echo "eagle is flying"

          docker system prune -af
