name: Deploy Production Version

on:
  pull_request_target:
    types:
    - closed
    branches: 
      - main

jobs:
  building-and-deploy-on-hub:
    if: github.event.pull_request.merged == true
    name: Build & Publish Aguia Project
    runs-on: ubuntu-latest
    env:
      CI: false
      DOCKER_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

    steps:
      - uses: actions/checkout@v2

      - name: Building production project
        run: |
          npm install
          npm run build
          cp Dockerfile ./dist
   
      - name: Publishing on EC2
        run: |
          echo "${{ secrets.SSH_PROD_PRIVATE_KEY }}" > ./key.pem
          chmod 400 ./key.pem
          eval $(ssh-agent)
          ssh-add -k ./key.pem

          mkdir -p ~/.ssh && echo "Host *" > ~/.ssh/config && echo " StrictHostKeyChecking no" >> ~/.ssh/config
          
          cd dist

          scp -r ./* ubuntu@ec2-15-229-88-93.sa-east-1.compute.amazonaws.com:/var/www/api
          
          docker image build \
            -t aguia-real \
            -f Dockerfile .
          
          docker run -d -p 49160:3001 aguia-real:latest